### PR TITLE
accept port ranges for ExposePorts config

### PR DESCRIPTION
**Pull request by marulitua**
As discussed at #66

### CODE REVIEW

**Comment by NHAS** [comment]
Hi there!

Thanks for this merge request and the effort you've put in to make this.


My only comment is that having the port range format using the dash (`-`) rather than `:` would be better as its consistent with the other places we define ports in wag.

I understand its written like this because iptables `--dport` takes that as its port range syntax.


And one small comment is I'm away from computer for a bit so will test and merge when I get back.

**Comment by marulitua** [comment]
Understood will update it

**Comment by marulitua** [comment]
Hi @NHAS please check when you have time

**Comment by NHAS** [comment]
Yep will do now

**Comment by NHAS** [comment]
Sweet looks good and I've just merged it onto the unstable branch. Thanks for all your work!

**Comment by marulitua** [comment]
Awesome! Many thanks.

**Pull request merged**
